name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use your EC2 instance as a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: sudo docker build -t my-html-app .

      - name: Stop and Remove Old Container (If Exists)
        run: |
          sudo docker stop my-html-container || true
          sudo docker rm my-html-container || true

      - name: Remove Old Image (If Exists)
        run: sudo docker rmi my-html-app || true

      - name: Run New Container
        run: sudo docker run -d -p 8080:80 --name my-html-container my-html-app
